In [1]:
import pandas as pd
import os
from dotenv import load_dotenv
from pandas import json_normalize
import json
import requests

First we insert the URL from the API and get the response in json format

In [7]:
url = 'http://api.nobelprize.org/2.1/laureates?limit=1000&sort=asc&format=json&csvLang=en'
parameters = {'accept': 'application/json'}
response = requests.get(url).json()

We make data visualization on the column where most of the information is located.

In [4]:
df = json_normalize(response["laureates"])

df.columns

Index(['id', 'fileName', 'gender', 'sameAs', 'links', 'nobelPrizes',
       'knownName.en', 'knownName.se', 'givenName.en', 'givenName.se',
       'familyName.en', 'familyName.se', 'fullName.en', 'fullName.se',
       'birth.date', 'birth.place.city.en', 'birth.place.city.no',
       'birth.place.city.se', 'birth.place.country.en',
       'birth.place.country.no', 'birth.place.country.se',
       'birth.place.cityNow.en', 'birth.place.cityNow.no',
       'birth.place.cityNow.se', 'birth.place.cityNow.sameAs',
       'birth.place.countryNow.en', 'birth.place.countryNow.no',
       'birth.place.countryNow.se', 'birth.place.countryNow.sameAs',
       'birth.place.continent.en', 'birth.place.continent.no',
       'birth.place.continent.se', 'birth.place.locationString.en',
       'birth.place.locationString.no', 'birth.place.locationString.se',
       'wikipedia.slug', 'wikipedia.english', 'wikidata.id', 'wikidata.url',
       'death.date', 'death.place.city.en', 'death.place.city.no',
       'death.place.city.se', 'death.place.country.en',
       'death.place.country.no', 'death.place.country.se',
       'death.place.country.sameAs', 'death.place.cityNow.en',
       'death.place.cityNow.no', 'death.place.cityNow.se',
       'death.place.cityNow.sameAs', 'death.place.countryNow.en',
       'death.place.countryNow.no', 'death.place.countryNow.se',
       'death.place.countryNow.sameAs', 'death.place.continent.en',
       'death.place.continent.no', 'death.place.continent.se',
       'death.place.locationString.en', 'death.place.locationString.no',
       'death.place.locationString.se', 'acronym', 'orgName.en', 'orgName.no',
       'orgName.se', 'founded.date', 'founded.place.city.en',
       'founded.place.city.no', 'founded.place.city.se',
       'founded.place.country.en', 'founded.place.country.no',
       'founded.place.country.se', 'founded.place.country.sameAs',
       'founded.place.cityNow.en', 'founded.place.cityNow.no',
       'founded.place.cityNow.se', 'founded.place.cityNow.sameAs',
       'founded.place.countryNow.en', 'founded.place.countryNow.no',
       'founded.place.countryNow.se', 'founded.place.countryNow.sameAs',
       'founded.place.continent.en', 'founded.place.continent.no',
       'founded.place.continent.se', 'founded.place.locationString.en',
       'founded.place.locationString.no', 'founded.place.locationString.se',
       'nativeName', 'penName', 'knownName.no', 'givenName.no',
       'familyName.no', 'fullName.no', 'foundedCountry.en',
       'foundedCountry.no', 'foundedCountry.se', 'foundedCountryNow.en',
       'foundedCountryNow.no', 'foundedCountryNow.se', 'foundedContinent.en'],
      dtype='object')

In [8]:
df

,id,fileName,gender,sameAs,links,nobelPrizes,knownName.en,knownName.se,givenName.en,givenName.se,...,givenName.no,familyName.no,fullName.no,foundedCountry.en,foundedCountry.no,foundedCountry.se,foundedCountryNow.en,foundedCountryNow.no,foundedCountryNow.se,foundedContinent.en
0,745,spence,male,"[https://www.wikidata.org/wiki/Q157245, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '2001', 'category': {'en': 'Eco...",A. Michael Spence,A. Michael Spence,A. Michael,A. Michael,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,102,bohr,male,"[https://www.wikidata.org/wiki/Q103854, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '1975', 'category': {'en': 'Phy...",Aage N. Bohr,Aage N. Bohr,Aage N.,Aage N.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,779,ciechanover,male,"[https://www.wikidata.org/wiki/Q233205, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '2004', 'category': {'en': 'Che...",Aaron Ciechanover,Aaron Ciechanover,Aaron,Aaron,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,259,klug,male,"[https://www.wikidata.org/wiki/Q190626, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '1982', 'category': {'en': 'Che...",Aaron Klug,Aaron Klug,Aaron,Aaron,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1004,gurnah,male,"[https://www.wikidata.org/wiki/Q317877, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '2021', 'category': {'en': 'Lit...",Abdulrazak Gurnah,Abdulrazak Gurnah,Abdulrazak,Abdulrazak,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,826,nambu,male,"[https://www.wikidata.org/wiki/Q188120, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '2008', 'category': {'en': 'Phy...",Yoichiro Nambu,Yoichiro Nambu,Yoichiro,Yoichiro,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
977,927,ohsumi,male,"[https://www.wikidata.org/wiki/Q8056214, https...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '2016', 'category': {'en': 'Phy...",Yoshinori Ohsumi,Yoshinori Ohsumi,Yoshinori,Yoshinori,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
978,265,lee,male,"[https://www.wikidata.org/wiki/Q243190, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '1986', 'category': {'en': 'Che...",Yuan T. Lee,Yuan T. Lee,Yuan T.,Yuan T.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
979,794,chauvin,male,"[https://www.wikidata.org/wiki/Q202146, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '2005', 'category': {'en': 'Che...",Yves Chauvin,Yves Chauvin,Yves,Yves,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
980,726,alferov,male,"[https://www.wikidata.org/wiki/Q183279, https:...","[{'rel': 'laureate', 'href': 'https://api.nobe...","[{'awardYear': '2000', 'category': {'en': 'Phy...",Zhores Alferov,Zhores Alferov,Zhores,Zhores,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# df.to_csv("../data/df.csv", index=False)